#!/usr/bin/env python3
"""Sync Cam standing schedules ↔ mesh/cline and emit Cline schedule import commands.

Does not require the cline binary. Writes:
  - identity/persistence/cline-schedules.export.json (mesh-ready)
  - updates cline-session-cache.json schedules[]
  - optional shell script with `cline schedule create/import` lines
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import cam_workspaces as cw  # noqa: E402


def load_schedules() -> dict:
    return cw.load_json(cw.SCHEDULES_PATH)


def export_mesh_doc(schedules: dict, reg: dict) -> dict:
    items = []
    for s in schedules.get("schedules") or []:
        ws_id = s.get("workspace_id")
        try:
            ws = cw.get_workspace(ws_id, reg)
            path = str(cw.resolve_workspace_path(ws))
        except KeyError:
            ws = None
            path = None
        items.append(
            {
                **s,
                "resolved_workspace_path": path,
                "workspace_exists": bool(ws and cw.workspace_exists(ws)),
            }
        )
    return {
        "namespace": "mesh/cline.schedules",
        "source": "config/workspaces/schedules.json",
        "synced_at": datetime.now(timezone.utc).isoformat(),
        "nullboiler_note": "Cam standing goals mirrored as Cline cron schedules; nullboiler remains team orchestrator",
        "schedules": items,
    }


def cline_commands(doc: dict) -> list[str]:
    cmds = []
    for s in doc.get("schedules") or []:
        if not s.get("enabled", True):
            cmds.append(f"# disabled: {s.get('id')}")
            continue
        path = s.get("resolved_workspace_path") or "."
        # Prefer schedule create for clarity; import YAML can be added later
        prompt = (s.get("prompt") or "").replace('"', '\\"')
        name = (s.get("name") or s.get("id") or "cam-schedule").replace('"', '\\"')
        timeout = s.get("timeout") or 1800
        tags = ",".join(s.get("tags") or [])
        cmds.append(
            "cline schedule create "
            f'"{name}" '
            f'--cron "{s.get("cron")}" '
            f'--prompt "{prompt}" '
            f"--workspace {path} "
            f"--timeout {timeout} "
            + (f'--tags {tags} ' if tags else "")
        )
    return cmds


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", help="write mesh schedules JSON")
    p.add_argument("--shell-out", help="write shell script of cline schedule create commands")
    p.add_argument("--apply-cache", action="store_true", help="update cline-session-cache.json")
    p.add_argument("--print-commands", action="store_true")
    args = p.parse_args()

    reg = cw.load_registry()
    schedules = load_schedules()
    doc = export_mesh_doc(schedules, reg)

    out = Path(args.out) if args.out else ROOT / "identity" / "persistence" / "cline-schedules.export.json"
    cw.write_json(out, doc)
    print(f"wrote {out}")

    if args.apply_cache:
        cache = cw.load_json(cw.CLINE_CACHE)
        cache["schedules"] = doc["schedules"]
        cache["schedules_synced_at"] = doc["synced_at"]
        cw.write_json(cw.CLINE_CACHE, cache)
        print(f"updated {cw.CLINE_CACHE}")

    cmds = cline_commands(doc)
    if args.print_commands:
        print("\n".join(cmds))
    if args.shell_out:
        sh = Path(args.shell_out)
        sh.parent.mkdir(parents=True, exist_ok=True)
        body = "#!/usr/bin/env bash\nset -euo pipefail\n# Generated by sync-cline-schedules.py\n" + "\n".join(cmds) + "\n"
        sh.write_text(body, encoding="utf-8")
        sh.chmod(0o755)
        print(f"wrote {sh}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
